### PR TITLE
Add --targetSubFolder to allow KuduSync to copy files from a source f…

### PR DESCRIPTION
**Pull request by ahmelsayed**
…older to a sub folder in the destination

### CODE REVIEW

**Comment by davidebbo** [comment]
:shipit:

**Comment by davidebbo** [comment]
Take that back. As discussed, deletions are broken.

**Comment by ahmelsayed** [comment]
5dc269d4aa31cbcb13c558df216d5eff7b94386b should fix the deletion issues. I ran through more scenarios manually and running kudu tests locally now.

**Comment by davidebbo** [comment]
Yes, seems to work fine now. :shipit:

**Pull request merged**
